### ISSUE TITLE
express-ws error with HTTPS server

### ISSUE THREAD

**Issue by Joshuaf91** [HenningM/express-ws#103]
Some background information I am running my server locally and trying to connect to my server using my ip address. When i attempt to connect my client to `wss://<IPADDRESS>:9000` I get an error cant read property 'length' of null.

I am using self signed certs created following these steps https://www.akadia.com/services/ssh_test_certificate.html.

Here is my full code base where Im still getting these issues.

`const https = require('https');
const fs = require('fs');
const express = require('express');
const bodyParser = require('body-parser');
const path = require('path');
const config = require('./config/config');
const app = express();
const expressWsLib = require('express-ws');
const WebSocket = require('ws');

function startServer () {
  const options = {
    key: fs.readFileSync(path.join(__dirname, 'etc/server.key'), 'utf8'),
    cert: fs.readFileSync(path.join(__dirname, 'etc/server.crt'), 'utf8')
  };
  const server = https.createServer(options, app);
  const expressWs = expressWsLib(app, server);
  app.use((req, res, next) => {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET, PUT, POST, DELETE');
    res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
    next();
  });
  app.use(bodyParser.urlencoded({ extended: true }));
  app.use(bodyParser.json());
  app.use(express.static(path.join(__dirname, './client')));
  app.get('/*', (req, res) => {
    res.sendFile(path.join(__dirname, 'client/index.html'));
  });
  

  // socket io
  // const io = require('socket.io')(server);

  // websocket
  app.ws('/', function(ws, req) {
    console.log('WS connected', expressWs.getWss().clients.size)
    ws.on('message', (message) => {
      console.log("messages",message + "\n");
      wssBroadcast(ws, message);
    })
    ws.on('close', () => {
      console.log(`Client disconnected. Total connected clients: ${ expressWs.getWss().clients.size}`)
    })
    
  });

  // Broadcast to all.
  wssBroadcast = (ws, data) => {
      expressWs.getWss().clients.forEach((client) => {
        console.log('client readyState', client.readyState)
        console.log('WebSocket.OPEN', WebSocket.OPEN)
          if (client !== ws && client.readyState === WebSocket.OPEN) {
              console.log('message sent')
              client.send(data);
          }
      });
  };
  server.listen(config.port, () => {
    console.log(`HTTP Listening on port ${config.port}`)
  })
}

startServer();

module.exports = {
  app,
};`

Here is the full stack trace from the error

`_http_outgoing.js:231
      this.outputSize += header.length;
                                ^

TypeError: Cannot read property 'length' of null
    at ServerResponse._send (_http_outgoing.js:231:33)
    at write_ (_http_outgoing.js:625:15)
    at ServerResponse.write (_http_outgoing.js:567:10)
    at ReadStream.ondata (_stream_readable.js:666:20)
    at ReadStream.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at ReadStream.Readable.push (_stream_readable.js:219:10)
    at lazyFs.read (internal/fs/streams.js:181:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:460:17)`

and a copy of my dependencies from my package.json file

`"dependencies": {
    "amqplib": "^0.5.2",
    "express": "^4.16.3",
    "express-ws": "^4.0.0",
    "nodemon": "^1.18.4",
    "socket.io": "^2.1.1"
  }
`

**Comment by xXCalleManXx** [comment]
Hi,

I have reproduced this error from the example provided in the README:
`const app = express();
  const expressWs = require('express-ws')(app);

  (app as any).ws('/', (ws, req) => {
    ws.on('message', msg => {
      console.log(msg);
    });
    console.log('socket', (req as any).testing);
  });

  http.createServer(app).listen(3000);`

If I use `app.listen(3000)` instead of `http.createServer(app).listen(3000)`.

Are there a solution for this?
