### ISSUE TITLE
undefined app.mountpath leads to crash

### ISSUE THREAD

**Issue by PSeitz** [HenningM/express-ws#11]
Hi,

I get this error, because app.mountpath is undefined in addSocketRoute.

url.js:107
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url)
          ^
TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:107:11)
    at urlParse (url.js:101:5)
    at Object.urlResolve [as resolve] (url.js:411:10)
    at Function.addSocketRoute [as ws] (/Users/d056831/Development/HomeAutomation.js/node_modules/express-ws/index.js:24:22)
    at Object.<anonymous> (/Users/d056831/Development/HomeAutomation.js/routes.js:39:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

```javascript
function addSocketRoute(route, middleware, callback) {
    var args = [].splice.call(arguments, 0);
    var wsPath = url.resolve(app.mountpath, route);
```

**Comment by PSeitz** [comment]
Hi, seems that I wanted to use routers, which are not supported currently. Therefore the mountpath was undefined
