### ISSUE TITLE
express-ws crashing the app repeatedly

### ISSUE THREAD

**Issue by TomMettam** [HenningM/express-ws#143]
My app is constantly restarting due to this uncaught exception in ws

```
RangeError: Invalid WebSocket frame: RSV1 must be clear
    at Receiver.getInfo (/home/www/caspercontrol-new/node_modules/express-ws/node_modules/ws/lib/receiver.js:167:14)
    at Receiver.startLoop (/home/www/caspercontrol-new/node_modules/express-ws/node_modules/ws/lib/receiver.js:121:22)
    at Receiver._write (/home/www/caspercontrol-new/node_modules/express-ws/node_modules/ws/lib/receiver.js:69:10)
    at writeOrBuffer (_stream_writable.js:352:12)
     at Receiver.Writable.write (_stream_writable.js:303:10)
    at Socket.socketOnData (/home/www/caspercontrol-new/node_modules/express-ws/node_modules/ws/lib/websocket.js:795:35)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
     at Socket.Readable.push (_stream_readable.js:217:10)
     at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
   [Symbol(status-code)]: 1002
 }
```

How can I cleanly handle this error and prevent the app from stopping?

**Comment by szabadkai** [comment]
I am experiencing the same issue. No regards to routes.

**Comment by mattvb91** [comment]
This problem seems to come from express itself. Ive had to go native to just use http.createServer without express to prevent this issue from happening.
