### ISSUE TITLE
Crash on connection

### ISSUE THREAD

**Issue by Perodactyl** [HenningM/express-ws#144]
I am using a slightly modified version of the echo example, however, when a client connects, the server crashes:
```
TypeError: Cannot read property 'length' of null
    at ServerResponse._send (_http_outgoing.js:320:33)
    at write_ (_http_outgoing.js:718:15)
    at ServerResponse.write (_http_outgoing.js:661:15)
    at ReadStream.ondata (internal/streams/readable.js:719:22)
    at ReadStream.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at ReadStream.Readable.push (internal/streams/readable.js:223:10)
    at internal/fs/streams.js:226:14
    at FSReqCallback.wrapper [as oncomplete] (fs.js:539:5)
```
My code is:
```
var settings = require("./storeInf")("settings.json")
var crs = require("./crypto")
var express = require("express")
var app = express()
var eWs = require("express-ws")(app)
function get(path){
    return (req, res)=>{
        res.sendFile(path, {"root":__dirname})
    }
}
app.get("/crypto.js", (get("crypto.js")))
app.get(/(\/|\/index\.html)/, (get("client.html")))
app.ws('/ws', function(ws, req) {
    ws.send(crs.encode({"type":"access", data:true}))
    ws.on('message', function(msg) {
      ws.send(msg);
    });
});
app.listen(80, ()=>{console.log("Listening.")})
```
What crypto.js and storeInf.js are is not important.

**Comment by Perodactyl** [comment]
Sorry, my code was not working.
