### ISSUE TITLE
Uncaught, unspecified "error" event.

### ISSUE THREAD

**Issue by fletchto99** [HenningM/express-ws#24]
I'm receiving this error occasionally which is causing my program to crash. I'm assuming it's because I don't handle the error event, but should this be the expected result? I would think that the error would just be ignored.

For reference here is the program: https://github.com/fletchto99/Pebble-liveconfig/blob/master/server/liveconfig.js

````js
liveconfig-0 Error: Uncaught, unspecified "error" event. (invalid error code)
liveconfig-0     at WebSocket.emit (events.js:157:17)
liveconfig-0     at Receiver.self._receiver.onerror (/usr/local/lib/node_modules/express-ws/node_modules/ws/lib/WebSocket.js:704:10)
liveconfig-0     at Receiver.error (/usr/local/lib/node_modules/express-ws/node_modules/ws/lib/Receiver.js:295:8)
liveconfig-0     at Receiver.opcodes.8.finish (/usr/local/lib/node_modules/express-ws/node_modules/ws/lib/Receiver.js:491:14)
liveconfig-0     at Receiver.<anonymous> (/usr/local/lib/node_modules/express-ws/node_modules/ws/lib/Receiver.js:472:33)
liveconfig-0     at Receiver.add (/usr/local/lib/node_modules/express-ws/node_modules/ws/lib/Receiver.js:87:24)
liveconfig-0     at Socket.firstHandler (/usr/local/lib/node_modules/express-ws/node_modules/ws/lib/WebSocket.js:663:22)
liveconfig-0     at emitOne (events.js:90:13)
liveconfig-0     at Socket.emit (events.js:182:7)
liveconfig-0     at readableAddChunk (_stream_readable.js:147:16)

**Comment by fletchto99** [comment]
Perhaps this issue is due to the out of date ws dependency? https://www.versioneye.com/nodejs/express-ws/0.2.6

**Comment by fletchto99** [comment]
The commit appears to fix it. Will keep this ticket open for now and will report back in a few days if I encounter any issues.

**Comment by HenningM** [comment]
Hi @fletchto99,

I'm closing this issue for now. Please reopen it if the problem occurs again.
