### ISSUE TITLE
Getting a stack trace when opening a connection and sending a test message.

### ISSUE THREAD

**Issue by antojk** [HenningM/express-ws#46]
I am getting the exception as mentioned in the following:
[stackout.txt](https://github.com/HenningM/express-ws/files/578471/stackout.txt)

The source of my server file is:
[server.txt](https://github.com/HenningM/express-ws/files/578476/server.txt)

**Comment by sxlijin** [comment]
Bump, having this issue as well.

```
$ node --version
v7.2.0
$ grep express package.json
    "express-session": "^1.14.2",
    "express-ws": "^2.0.0",
```

It happens specifically when _any_ websocket connection to the server is opened:
```
_http_outgoing.js:138
      this.outputSize += this._header.length;
                                     ^

TypeError: Cannot read property 'length' of null
    at ServerResponse._send (_http_outgoing.js:138:38)
    at ServerResponse.write (_http_outgoing.js:494:16)
    at ReadStream.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ReadStream.Readable.push (_stream_readable.js:134:10)
    at onread (fs.js:1838:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:602:17)
```

**Comment by joepie91** [comment]
@antojk: What version of Node.js are you experiencing this issue on?

Also, aside from the issue you're reporting, the following code is incorrect:

```js
// Echo all messages to all listeners
app.ws(channel, function(ws, req) {
    ws.on('add', function(msg) {
        ws.send(msg);
    });
    ws.on('update', function(msg) {
        ws.send(msg);
    });
    ws.on('delete', function(msg) {
        ws.send(msg);
    });
    console.log('Socket broadcast: ', req.testing);
});
```

There are no `add`, `update` or `delete` events on a standard WebSocket - there's only a `message` event, which you're responsible for serializing/deserializing yourself. In other words, the implementation of "commands" is left up to the implementation, and not defined by the WebSocket library.

--

@sxlijin: Does your code also contain an `app.get("*")` route or something along those lines? It looks like that might be interfering with the 'fake' route that `express-ws` creates for dealing with middleware.

**Comment by joepie91** [comment]
@HenningM Absent any response from the original posters indicating otherwise, maybe we should treat this as a dupe of #64 (which has a clear minimal testcase) and close this issue?

**Comment by sxlijin** [comment]
@joepie91 unfortunately I have no idea what code I was trying out when I bumped this issue. I'm happy to test MWE's to verify a fix, but I no longer have any skin in this issue.
