### ISSUE TITLE
Cannot set property ws of undefined

### ISSUE THREAD

**Issue by quesurifn** [HenningM/express-ws#77]
Hello, 

On connection I get ```
Users/kylecameronryanfahey/Documents/Github/serverSentiment/node_modules/express-ws/lib/index.js:69
    request.ws = socket;
               ^

TypeError: Cannot set property 'ws' of undefined
    at WebSocketServer.<anonymous> (/Users/kylecameronryanfahey/Documents/Github/serverSentiment/node_modules/express-ws/lib/index.js:69:16)
    at emitTwo (events.js:106:13)
    at WebSocketServer.emit (events.js:194:7)
    at handleUpgrade (/Users/kylecameronryanfahey/Documents/Github/serverSentiment/node_modules/ws/lib/WebSocketServer.js:88:16)
    at WebSocketServer.completeUpgrade (/Users/kylecameronryanfahey/Documents/Github/serverSentiment/node_modules/ws/lib/WebSocketServer.js:270:5)
    at WebSocketServer.handleUpgrade (/Users/kylecameronryanfahey/Documents/Github/serverSentiment/node_modules/ws/lib/WebSocketServer.js:197:10)
    at Server.WebSocketServer._ultron.on (/Users/kylecameronryanfahey/Documents/Github/serverSentiment/node_modules/ws/lib/WebSocketServer.js:87:14)
    at emitThree (events.js:116:13)
    at Server.emit (events.js:197:7)
    at onParserExecuteCommon (_http_server.js:462:14)
    at onParserExecute (_http_server.js:421:3)

```

Google doesn't turn up anything...

Routes:

```
var express = require('express');
var router = express.Router();
require('express-ws')(router);
require('dotenv').config()

var Twit = require('twit')
 
var T = new Twit({
  consumer_key:         process.env.TWITTER_CONSUMER_KEY,
  consumer_secret:      process.env.TWITTER_CONSUMER_SECRET,
  access_token:         process.env.TWITTER_ACCESS_TOKEN,
  access_token_secret:  process.env.TWITTER_ACCESS_SECRET,
})

router.ws('/', function(ws, req) {
   ws.on('message', function(msg) {
    ws.send(msg);
  });
})

router.ws('/tweets', function(ws, req) {
  ws.on('connect', function(req) {
    console.log(req)
    ws.send(req);
  });
  const stream = T.stream('statuses/filter', { track: ['POTUS', 'trump', 'president', 'realDonaldTrump'] })
  stream.on('tweet', function(tweet){
    console.log(tweet)
    ws.send(tweet)
  })
 stream.on('disconnect', function (disconn) {
  console.log('disconnect')
  })

stream.on('connect', function (conn) {
  console.log('connecting')
})

stream.on('reconnect', function (reconn, res, interval) {
  console.log('reconnecting. statusCode:', res.statusCode)
  })
})

router.ws('/trump', function(ws, req) {
  const stream = T.stream('statuses/user_timeline', { screen_name: ['POTUS', 'realDonaldTrump'] })
  stream.on('tweet', function(tweet) {
    console.log(tweet)
    ws.send(tweet)
  })
})

module.exports = router;
```


App: 

```
var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');

var app = express();
var server = require('http').Server(app);
var expressWs = require('express-ws')(app,server);

var index = require('./routes/index');
// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

// uncomment after placing your favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', index);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = {app: app,server: server};

```

bin/www


```
#!/usr/bin/env node

/**
 * Module dependencies.
 */

var app = require('../app').app;
var server = require('../app').server;
var debug = require('debug')('serversentiment:server');
var http = require('http');

/**
 * Get port from environment and store in Express.
 */

var port = normalizePort(process.env.PORT || '3000');
app.set('port', port);

/**
 * Create HTTP server.
 */

//var server = http.createServer(app);

/**
 * Listen on provided port, on all network interfaces.
 */

server.listen(port);
server.on('error', onError);
server.on('listening', onListening);

/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  debug('Listening on ' + bind);
}

```


If someone could tell me how to set it up with clustering I'd very much appreciate it!!

**Comment by yacinehmito** [comment]
I tracked the error to here: https://github.com/websockets/ws/pull/1104

I'll try a fix.

**Comment by yacinehmito** [comment]
I just published [@yacinehmito/express-ws](https://www.npmjs.com/package/@yacinehmito/express-ws) if you urgently need a version of express-ws that works with ws v3.0.
